id: P010412
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 20:48:24.529208
source_metadata:
  id: bdr:W3CN4278
  title: དབུ་མ་རྒྱན་འཇུག་པ་བཞི་བརྒྱ་པའི་རྩ་བ།
  author: ''
  volumes:
    41fabc8a151d445d9d69e6f0e4fc126c:
      image_group_id: I3CN4302
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
