id: P010412
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4278
  title: དབུ་མ་རྒྱན་འཇུག་པ་བཞི་བརྒྱ་པའི་རྩ་བ།
  author: ''
  volumes:
    41fabc8a151d445d9d69e6f0e4fc126c:
      image_group_id: I3CN4302
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
